# Generated by Django 4.2 on 2026-04-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0002_recipie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
