# Generated by Django 4.2 on 2026-04-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0003_user_images_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50),
        ),
    ]
