# Generated by Django 4.2 on 2026-04-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0004_alter_recipie_difficulty_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipie',
            old_name='foreign_key',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='recipie',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50),
        ),
    ]
