# Generated by Django 4.2 on 2026-04-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0005_rename_foreign_key_recipie_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipie',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
