# Generated by Django 4.2 on 2026-05-05 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipie', '0006_alter_recipie_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='images',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
